version: '3'

services:
#  app:
#    build: ./gateway
#    ports:
#      - "8000:8000"
  app2:
    build: ./pokemon_server
    ports:
      - "8001:8001"
    depends_on:
      - mysql
#  app3:
#    build: ./external_api
#    ports:
#      - "8002:8002"
  app4:
    build: ./pokemon_img_server
    ports:
      - "8003:8003"
    depends_on:
      - mongodb
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"